final_project/config/routes.rb
Rails.application.routes.draw do

  get 'map' => 'images#map', as:"map"
	get 'photos' => 'images#photos'
  get '/' => 'users#welcome', as:"welcome"
  get '/about' => 'users#about', as:"about"
  get 'signup' => 'users#new'

  get '/users/:user_id/images/:id/like' => 'images#like', as:"like"
  get '/users/:user_id/images/:id/original' => 'images#original', as:"original"

  get 'login' => 'sessions#new'
  get 'images/search' => 'images#get_search', as:"search"
  get 'images/update_map' => 'images#get_update_map', as:"update_map"
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users do
    resources :images
  end

end

final_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalProject</title>

  <%= javascript_include_tag 'application'%>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>

<!-- <script src="https://maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script> -->
<script src='https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <%= csrf_meta_tags %>

</head>
<body>

	<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to("Home", welcome_path, class: "navbar-brand") %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          	<li><%= link_to("Gallery", photos_path) %></li>
            <li><%= link_to("Map", map_path) %></li>
            <li><%= link_to("Users", users_path) %></li>
            <li><a href="">About us</a></li>
            <li><a href="">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
      			<% if current_user %> 
      				  <li id="user-name"><%= link_to("Welcome "+current_user.name, user_path(current_user)) %></li>
      			    <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
      			<% else %> 
      			    <li><%= link_to "Login", 'login' %></a></li> 
      			    <li><%= link_to "Signup", 'signup' %></a></li> 
      			<% end %>
          </ul>
        </div>
      </div>
    </nav>

<!-- Esto es para que la barra de navegación no ocupe la parte superior del título -->
    <br>
    <br>

<%= yield %>


<% if @layout_welcome != false %>
  <footer class="footer">
    <div class="container col-xs-12 col-md-12">
      <br><br>
      <p class="text-muted">Created by @ngel. 2015</p>
    </div>
  </footer>
<% end %>


<!-- <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>
-->

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

</body>
</html>