final_project/config/routes.rb
Rails.application.routes.draw do

  get 'map' => 'images#map', as:"map"
	get 'photos' => 'images#photos'
  get '/' => 'users#welcome', as:"welcome"
  get '/about' => 'users#about', as:"about"
  get 'signup' => 'users#new'

  get '/users/:user_id/images/:id/like' => 'images#like', as:"like"
  get '/users/:user_id/images/:id/original' => 'images#original', as:"original"

  get 'login' => 'sessions#new'
  get 'images/search' => 'images#get_search', as:"search"
  get 'images/update_map' => 'images#get_update_map', as:"update_map"
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users do
    resources :images
  end

end

final_project/app/models/image.rb
class Image < ActiveRecord::Base

	belongs_to :user
	
	validates :title, presence: true 
	validates :address, presence: true
	validates :description, presence: true 
	validates :theme, presence: true 


	serialize :users_likes, Array
	#serialize lo que hace es convertir ese atributo a ese elemento de forma obligada

	geocoded_by :address	

	

	has_attached_file :photo, :styles => { :medium => "300x300#", :thumb => "100x100#", :large => "500x500#" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

	after_validation :geocode

end

final_project/app/controllers/images_controller.rb
class ImagesController < ApplicationController

	before_action :require_user, only: [:index, :show, :edit, :destroy, :new, :create]
	#before_action :require_editor, only: [:edit]
	#before_action :require_admin, only: [:destroy]

	def index
		@user = User.find params[:user_id] #el corchete con params tiene que ir junto!!
		@images = @user.images
	end

	def map
		@layout_welcome = false
		
		@images = Image.all

		@hash = Gmaps4rails.build_markers(@images) do |image, marker|
	 		marker.lat image.latitude
	 		marker.lng image.longitude
	 		marker.json({:id => image.id })
	 		title = view_context.link_to image.title, user_image_path(image.user_id, image)
	 		photo = view_context.image_tag(image.photo.url(:thumb))
	 		marker.infowindow title
	 	end 
	end

	def photos
		@array_images = Image.all
		@images_sorted = @array_images.sort_by {|image| image.likes}
		@images = @images_sorted.reverse

		respond_to do |format|
			format.html #{ render index: @images } ESTO EN ESTE CASO PUEDE OMITIRSE
    	format.json { render json: @images }
		end
	end

	def show
		@user = User.find params[:user_id]
		@image = @user.images.find params[:id]

		@hash = Gmaps4rails.build_markers(@image) do |image, marker|
	 		marker.lat image.latitude
	 		marker.lng image.longitude
	 		marker.json({:id => image.id })
	 	end 

	 	respond_to do |format|
			format.html #{ render index: @comments } ESTO EN ESTE CASO PUEDE OMITIRSE
    	format.json { render json: @image }
		end	
	end

	def get_update_map
		array_ids = params[:item]

		@images = []
		array_ids.each do |array_id|
			image = Image.find array_id 
			@images << image
		end

		@hash = Gmaps4rails.build_markers(@images) do |image, marker|
	 		marker.lat image.latitude
	 		marker.lng image.longitude
	 		marker.json({:id => image.id })
	 		image_link = view_context.link_to image.title,  user_image_path(image.user_id, image)
	 		marker.infowindow image_link
	 	end 	
		render 'update_map', layout: false
	end

	def get_search
		image_id = params[:item]
		@image = Image.find image_id
		render 'search', layout: false
	end

	def new
		@user = User.find params[:user_id]
		@image = @user.images.new
	end

	def create
		@user = User.find params[:user_id]
		@image = @user.images.new image_params

		if @image.save
			flash[:notice] = "Image uploaded successfully"
			redirect_to user_image_path(@user, @image) #le pasamos el @project para que tenga una forma de ver el parámetro project_id sobre el que tiene que coger las entries
		else
			flash[:alert] = "Photo hasn't been created!"
			render 'new'
		end
	end

	def edit
		@user = User.find params[:user_id]
		@image = @user.images.find params[:id]
	end

	def update
		@user = User.find params[:user_id]
		@image = @user.images.find params[:id]

		if @image.update image_params
			flash[:notice] = "Image updated successfully"
			redirect_to user_image_path(@user, @image)
		else
			flash.now[:errors] = @image.errors.full_messages #flash.now es para que el render no se lo coma y así poder usar el flash con el render
			render 'edit'
		end
	end

	def like
		@user = User.find params[:user_id]
		@image = @user.images.find params[:id]

		@image.likes =(@image.likes + 1)
		@image.users_likes << current_user.name
    	@image.save

     	redirect_to user_image_path(@user, @image) 
	end

	def original
		@user = User.find params[:user_id]
		@image = @user.images.find params[:id]
	end

	def destroy
		@user = User.find params[:user_id]
		@image = @user.images.find params[:id]
		@image.destroy
		redirect_to user_path(@user)
	end

	private
	def image_params
		params.require(:image).permit(:title, :theme, :description, :likes, :users_likes, :photo, :address, :latitude, :longitude)
	end

end

final_project/app/helpers/images_helper.rb
module ImagesHelper
end

final_project/app/views/images/edit.html.erb
<% if flash[:alert] %>
  <div class="alert alert-warning" role="alert">
        <strong><%= flash[:alert] %></strong>
  </div>
<% end %>

<% if @image.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% @image.errors.full_messages.each do |error_msg| %>
        <div><%= error_msg %></div>
      <% end %>
    </ul>
  </div>
<% end %>

<h2 class="form-signin-heading title">Modify your picture!</h2>

<div class="container col-md-5 col-md-offset-1 new-session">

        <%= form_for [@user, @image], :html => { :multipart => true} do |f| %>
    
        <div class="form-group">
          <div class="input-group input-group-lg">
            <span class="input-group-addon" id="sizing-addon1">Title</span>
            <%= f.text_field :title, :placeholder => "Put a title!", class: "form-control"  %>
          </div>
        </div>

        <div class="form-group">
          <div class="input-group input-group-lg">
            <span class="input-group-addon" id="sizing-addon1">Address</span>
            <%= f.text_field :address, :placeholder => "Where did you take it?", id: "pac-input", class: "form-control controls"  %>
          </div>
        </div>

     <!-- latitude y longitude estan ocultos pero no podemos eliminarlos para que funcione address -->
        <div class="form-group" hidden>
          <div class="input-group input-group-lg">
            <span class="input-group-addon" id="sizing-addon1">latitude</span>
            <%= f.text_field :latitude, :placeholder => "latitude!", class: "form-control"  %>
          </div>
        </div>

        <div class="form-group" hidden>
          <div class="input-group input-group-lg">
            <span class="input-group-addon" id="sizing-addon1">longitude</span>
            <%= f.text_field :longitude, :placeholder => "longitude!", class: "form-control"  %>
          </div>
        </div>

        <div class="form-group">
          <div class="input-group input-group-lg">
            <span class="input-group-addon" id="sizing-addon1">Theme</span>
              <select <%= f.text_field :theme, :placeholder => "Choose the type of place you want to share!", class: "form-control col-md-10" %>>
                <option>Monument</option>
                <option>Natural</option>
                <option>Art</option>
                <option>Entertainment</option>
                <option>Landscape</option>
                <option>Other</option>
              </select>
          </div>
        </div>

        <div class="form-group">
          <div class="input-group input-group-lg">
            <span class="input-group-addon" id="sizing-addon1">Description</span>
            <%= f.text_field :description, :placeholder => "Why do you want to share it?", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
            <%= f.file_field :photo, :placeholder => "Pick the file", class: "form-control"%>
        </div>

        
        <%= f.submit "SAVE", class: "btn btn-success col-xs-12 col-md-12" %>
        <br>
        <%= link_to("CANCEL", user_image_path(@user, @image), class: "btn btn-warning col-xs-12 col-md-12") %>
      <% end %>
</div> 


<div id="map-new" class="col-md-5">
  <div id="map" style='width: 100%; height: 100%;'></div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
    provider: {
      zoom : 14,
      mapTypeId : google.maps.MapTypeId.ROADMAP,
    },
    internal: {
      id: 'map'
    }
  });
</script>

<script type="text/javascript">
function initialize(){
    var mapOptions = {
      zoom: 6,
      center: new google.maps.LatLng(40.353715, -3.702213)
    };

    var map = new google.maps.Map(document.getElementById('map'),
      mapOptions);

    var defaultBounds = new google.maps.LatLngBounds(
        new google.maps.LatLng(44.338437, -10.228092),
        new google.maps.LatLng(36.561334, 1.681087));
    var options = {
        bounds: defaultBounds
    };

    var input = document.getElementById('pac-input');
    var autocomplete = new google.maps.places.Autocomplete(input);
    autocomplete.bindTo('bounds', map);

      var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map,
    anchorPoint: new google.maps.Point(0, -29)
  });

  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    infowindow.close();
    marker.setVisible(false);
    var place = autocomplete.getPlace();
    if (!place.geometry) {
      window.alert("Autocomplete's returned place contains no geometry");
      return;
    }

    // If the place has a geometry, then present it on a map.
    if (place.geometry.viewport) {
      map.fitBounds(place.geometry.viewport);
    } else {
      map.setCenter(place.geometry.location);
      map.setZoom(17);  // Why 17? Because it looks good.
    }
    marker.setIcon(/** @type {google.maps.Icon} */({
      url: place.icon,
      size: new google.maps.Size(71, 71),
      origin: new google.maps.Point(0, 0),
      anchor: new google.maps.Point(17, 34),
      scaledSize: new google.maps.Size(35, 35)
    }));
    marker.setPosition(place.geometry.location);
    marker.setVisible(true);

    var address = '';
    if (place.address_components) {
      address = [
        (place.address_components[0] && place.address_components[0].short_name || ''),
        (place.address_components[1] && place.address_components[1].short_name || ''),
        (place.address_components[2] && place.address_components[2].short_name || '')
      ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    infowindow.open(map, marker);
  });
};

google.maps.event.addDomListener(window, 'load', initialize);
</script>

final_project/app/views/images/index.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>

<h1><%= @user.name %></h1>
<ul>
	<% @images.each do |image| %>
		<li>
			<%= image.title %> 
			<%= image.theme %> 
			<%= image.description %>
			<%= image.likes %>
		</li>
	<% end %>
</ul>

<ul>
<%= link_to("users", users_path) %>
<%= link_to("New image", new_user_image_path(@user)) %>
</ul>

final_project/app/views/images/map.html.erb
<center>
<div class="container">
    <div class="well well-md text-center col-md-12">
        <div class="btn-group col-md-12" id="search-in-map" data-toggle="buttons">
            <label class="btn btn-success col-xs-4 col-md-2">
                <input type="checkbox" autocomplete="off" value="Monument" />
                <span class="glyphicon glyphicon-camera"></span>
                <p>Monument</p>
            </label>
            <label class="btn btn-success col-xs-4 col-md-2">
                <input type="checkbox" autocomplete="off" value="Natural" />
                <span class="glyphicon glyphicon-tree-deciduous"></span>
                <p>Natural</p>
            </label>
            <label class="btn btn-success col-xs-4 col-md-2">
                <input type="checkbox" autocomplete="off" value="Art"/>
                <span class="glyphicon glyphicon-blackboard"></span>
                <p>Art</p>
            </label>
            <label class="btn btn-success col-xs-4 col-md-2">
                <input type="checkbox" autocomplete="off" value="Entertainment"/>
                <span class="glyphicon glyphicon-glass"></span>
                <p>Entertainment</p>
            </label>
            <label class="btn btn-success col-xs-4 col-md-2">
                <input type="checkbox" autocomplete="off" value="Landscape"/>
                <span class="glyphicon glyphicon-picture"></span>
                <p>Landscape</p>
            </label>
            <label class="btn btn-success col-xs-4 col-md-2">
                <input type="checkbox" autocomplete="off" value="Other"/>
                <span class="glyphicon glyphicon-question-sign"></span>
                <p>Other</p>
            </label>

        </div>
    </div>
</div>
</center>

  
  <div id="mapa-space"></div>

  <div id="mapa_div" class="col-md-8 col-md-offset-1">
    <div id="map" style='width: 100%; height: 100%;'></div>
  </div>


  <script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({
      provider: {
        zoom : 14,
        mapTypeId : google.maps.MapTypeId.ROADMAP,
      },
      internal: {
        id: 'map'
      }
    },
    function(){
    	markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    }
  );
  </script>

final_project/app/views/images/new.html.erb
<% if flash[:alert] %>
<div class="alert alert-warning" role="alert">
      <strong><%= flash[:alert] %></strong>
</div>
<% end %>

<% if @image.errors.any? %>
<div class="alert alert-danger" role="alert">
  <ul>
		<% @image.errors.full_messages.each do |error_msg| %>
		  <div><%= error_msg %></div>
		<% end %>
	</ul>
</div>
<% end %>

<h2 class="form-signin-heading title">Add a new photo!</h2>

<div class="container col-md-5 col-md-offset-1 new-session">

      <%= form_for [@user, @image], :html => { :multipart => true} do |f| %>
	
      <div class="form-group">
        <div class="input-group input-group-lg">
          <span class="input-group-addon" id="sizing-addon1">Title</span>
          <%= f.text_field :title, :placeholder => "Put a title!", class: "form-control"  %>
        </div>
      </div>

      <div class="form-group">
        <div class="input-group input-group-lg">
          <span class="input-group-addon" id="sizing-addon1">Address</span>
          <%= f.text_field :address, :placeholder => "Where did you take it?", id: "pac-input", class: "form-control controls"  %>
        </div>
      </div>

   <!-- latitude y longitude estan ocultos pero no podemos eliminarlos para que funcione address -->
      <div class="form-group" hidden>
        <div class="input-group input-group-lg">
          <span class="input-group-addon" id="sizing-addon1">latitude</span>
          <%= f.text_field :latitude, :placeholder => "latitude!", class: "form-control"  %>
        </div>
      </div>

      <div class="form-group" hidden>
        <div class="input-group input-group-lg">
          <span class="input-group-addon" id="sizing-addon1">longitude</span>
          <%= f.text_field :longitude, :placeholder => "longitude!", class: "form-control"  %>
        </div>
      </div>

      <div class="form-group">
        <div class="input-group input-group-lg">
          <span class="input-group-addon" id="sizing-addon1">Theme</span>
            <select <%= f.text_field :theme, :placeholder => "Choose the type of place you want to share!", class: "form-control col-md-10" %>>
              <option>Monument</option>
              <option>Natural</option>
              <option>Art</option>
              <option>Entertainment</option>
              <option>Landscape</option>
              <option>Other</option>
            </select>
        </div>
      </div>

      <div class="form-group">
        <div class="input-group input-group-lg">
          <span class="input-group-addon" id="sizing-addon1">Description</span>
          <%= f.text_field :description, :placeholder => "Why do you want to share it?", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
          <%= f.file_field :photo, :placeholder => "Pick the file", class: "form-control"%>
      </div>

      
      <%= f.submit "SAVE", class: "btn btn-success col-xs-12 col-md-12" %>
      <br>
      <%= link_to("CANCEL", user_path(@user), class: "btn btn-warning col-xs-12 col-md-12") %>
    <% end %>
</div> 


<div id="map-new" class="col-md-5">
  <div id="map" style='width: 100%; height: 100%;'></div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
    provider: {
      zoom : 14,
      mapTypeId : google.maps.MapTypeId.ROADMAP,
    },
    internal: {
      id: 'map'
    }
  });
</script>

<script type="text/javascript">
function initialize(){
    var mapOptions = {
      zoom: 6,
      center: new google.maps.LatLng(40.353715, -3.702213)
    };

    var map = new google.maps.Map(document.getElementById('map'),
      mapOptions);

    var defaultBounds = new google.maps.LatLngBounds(
        new google.maps.LatLng(44.338437, -10.228092),
        new google.maps.LatLng(36.561334, 1.681087));
    var options = {
        bounds: defaultBounds
    };

    var input = document.getElementById('pac-input');
    var autocomplete = new google.maps.places.Autocomplete(input);
    autocomplete.bindTo('bounds', map);

      var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map,
    anchorPoint: new google.maps.Point(0, -29)
  });

  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    infowindow.close();
    marker.setVisible(false);
    var place = autocomplete.getPlace();
    if (!place.geometry) {
      window.alert("Autocomplete's returned place contains no geometry");
      return;
    }

    // If the place has a geometry, then present it on a map.
    if (place.geometry.viewport) {
      map.fitBounds(place.geometry.viewport);
    } else {
      map.setCenter(place.geometry.location);
      map.setZoom(17);  // Why 17? Because it looks good.
    }
    marker.setIcon(/** @type {google.maps.Icon} */({
      url: place.icon,
      size: new google.maps.Size(71, 71),
      origin: new google.maps.Point(0, 0),
      anchor: new google.maps.Point(17, 34),
      scaledSize: new google.maps.Size(35, 35)
    }));
    marker.setPosition(place.geometry.location);
    marker.setVisible(true);

    var address = '';
    if (place.address_components) {
      address = [
        (place.address_components[0] && place.address_components[0].short_name || ''),
        (place.address_components[1] && place.address_components[1].short_name || ''),
        (place.address_components[2] && place.address_components[2].short_name || '')
      ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    infowindow.open(map, marker);
  });
};

google.maps.event.addDomListener(window, 'load', initialize);
</script>

final_project/app/views/images/original.html.erb
<div class="container-original">

    <h1 class="title col-md-11"><%= @image.title %></h1>

    <% if current_user && current_user.get_email == @user.email %>
        <div class="container col-md-6 container-buttoms">
            <%= link_to "Back", user_image_path(@user, @image), class: "btn btn-warning" %>
            <%= link_to "New", new_user_image_path(@user), class: "btn btn-success" %>
            <%= link_to "Edit", edit_user_image_path(@user, @image), class: "btn btn-info" %>
            <%= link_to "Destroy", user_image_path(@user, @image), method: :delete,
        data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
        </div>
    <% else %>
        <div class="col-md-6 col-md-offset-1 individual-buttom">
            <%= link_to "Back", photos_path, class: "btn btn-warning" %>
        </div>
    <% end %>
</div>

<div class="container col-md-12"></div>

<div class="container col-md-10 col-md-offset-1">

  <div class="row col-md-12" id="image"><%= image_tag @image.photo.url(:original), class: "img-thumbnail" %></div>

  <div class="container panel-effects col-md-10 col-md-offset-1">
  	<div class="panel panel-primary">
          <div class="panel-heading">
              <h3 class="panel-title"><i class="fa fa-magnet"></i> Want to see that place from a new perspective? Try this!</h3>
          </div>
          <div class="panel-body">
              <div class="btn btn-md btn-hover btn-default" id="gray">Gray</div>
              <div class="btn btn-md btn-hover btn-primary" id="saturate">Saturate</div>
              <div class="btn btn-md btn-hover btn-info" id="contrast">Contrast</div>
              <div class="btn btn-md btn-hover btn-warning" id="blur">Blur</div>
              <div class="btn btn-md btn-hover btn-danger" id="invert">Invert</div>
              <div class="btn btn-md btn-hover btn-success" id="rotate">Rotate</div>
          </div>
      </div>
  </div>     
</div>

final_project/app/views/images/photos.html.erb
<center>
<div class="container">
    <div class="well well-md text-center col-md-12">
        <div class="btn-group col-md-12" id="search-button" data-toggle="buttons">
            <label class="btn btn-success col-xs-4 col-md-2">
                <input type="checkbox" autocomplete="off" value="Monument" />
                <span class="glyphicon glyphicon-camera"></span>
                <p>Monument</p>
            </label>
            <label class="btn btn-success col-xs-4 col-md-2">
                <input type="checkbox" autocomplete="off" value="Natural" />
                <span class="glyphicon glyphicon-tree-deciduous"></span>
                <p>Natural</p>
            </label>
            <label class="btn btn-success col-xs-4 col-md-2">
                <input type="checkbox" autocomplete="off" value="Art"/>
                <span class="glyphicon glyphicon-blackboard"></span>
                <p>Art</p>
            </label>
            <label class="btn btn-success col-xs-4 col-md-2">
                <input type="checkbox" autocomplete="off" value="Entertainment"/>
                <span class="glyphicon glyphicon-glass"></span>
                <p>Entertainment</p>
            </label>
            <label class="btn btn-success col-xs-4 col-md-2">
                <input type="checkbox" autocomplete="off" value="Landscape"/>
                <span class="glyphicon glyphicon-picture"></span>
                <p>Landscape</p>
            </label>
            <label class="btn btn-success col-xs-4 col-md-2">
                <input type="checkbox" autocomplete="off" value="Other"/>
                <span class="glyphicon glyphicon-question-sign"></span>
                <p>Other</p>
            </label>

        </div>
    </div>
</div>
</center>

<div class="container photo-list">


</div>

final_project/app/views/images/search.html.erb
<div class="photo-container container col-xs-12 col-sm-6 col-md-4">
	<div class="row"> 
		<%= link_to image_tag(@image.photo.url(:medium)), user_image_path(@image.user_id, @image), class: "img-thumbnail" %>
	</div>
	<h4 class="row">
		<%= @image.title %>
	</h4>
	<div class="row">
		<% user = User.find(@image.user_id) %>
		Uploaded by <%= link_to(user.name, user_path(@image.user_id)) %>
		in <%= @image.created_at.day.to_s+"/"+@image.created_at.month.to_s+"/"+@image.created_at.year.to_s %>
	</div>
</div>

final_project/app/views/images/show.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success" role="success">
        <strong></strong><%= flash[:notice] %>
	</div>
<% end %>


<h1 class="title col-md-11"><%= @image.title %></h1>

    <% if current_user && current_user.get_email == @user.email %>
        <div class="container col-md-6 container-buttoms">
            <%= link_to "Back", photos_path, class: "btn btn-warning" %>
          	<%= link_to "New", new_user_image_path(@user), class: "btn btn-success" %>
          	<%= link_to "Edit", edit_user_image_path(@user, @image), class: "btn btn-info" %>
          	<%= link_to "Destroy", user_image_path(@user, @image), method: :delete,
    		data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
        </div>
    <% else %>
        <div class="col-md-6 col-md-offset-1 individual-buttom">
            <%= link_to "Back", photos_path, class: "btn btn-warning" %>
        </div>
    <% end %>

<div class="container col-md-12"></div>

<div class="container col-md-6 container-photo-original">

    <div class="row">
    <%= link_to image_tag(@image.photo.url(:large)), original_path(@image.user_id, @image), class: "img-thumbnail photo-original" %></div>

    <div class="img-thumbnail image-text col-md-10 col-md-offset-1">
  		<div class="row col-md-10 col-md-offset-1"><span class="shadow">Place: </span><%= @image.address %></div>
      <div class="row col-md-10 col-md-offset-1"><span class="shadow">Uploaded by: </span><%= link_to(@user.name, user_path(@image.user_id)) %></div>
      
  		<div class="row col-md-10 col-md-offset-1"><span class="shadow">What has to tell the uploader: </span><%= @image.description %></div>

      <center>
        <div class="row col-md-10 col-md-offset-1">
          <div class="btn-primary btn-circle btn-like">
            <span class="like"><%= @image.likes %> </span><span class="glyphicon glyphicon-thumbs-up"></span>
          </div>
        </div>
      </center>      
    </div>
</div>

<div class="mapa_single container col-sm-12 col-md-5">
  <div id="map" style='width: 100%; height: 100%;'></div>
</div>


<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
    provider: {
      zoom : 10,
      mapTypeId : google.maps.MapTypeId.ROADMAP,
    },
    internal: {
      id: 'map'
    }
  },
  function(){
  	markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(14);
  }
);

</script>

final_project/app/views/images/update_map.html.erb
  <div id="mapa_div" class="col-md-8 col-md-offset-1">
    <div id="map" style='width: 100%; height: 100%;'></div>
  </div>


<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
    provider: {
      zoom : 14,
      mapTypeId : google.maps.MapTypeId.ROADMAP,
    },
    internal: {
      id: 'map'
    }
  },
  function(){
  	markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  }
);
</script>