final_project/config/routes.rb
Rails.application.routes.draw do

  get 'map' => 'images#map', as:"map"
	get 'photos' => 'images#photos'
  get '/' => 'users#welcome', as:"welcome"
  get '/about' => 'users#about', as:"about"
  get 'signup' => 'users#new'

  get '/users/:user_id/images/:id/like' => 'images#like', as:"like"
  get '/users/:user_id/images/:id/original' => 'images#original', as:"original"

  get 'login' => 'sessions#new'
  get 'images/search' => 'images#get_search', as:"search"
  get 'images/update_map' => 'images#get_update_map', as:"update_map"
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users do
    resources :images
  end

end

final_project/app/models/user.rb
class User < ActiveRecord::Base
	has_many :images, :dependent => :destroy
	#ESTO ES NECESARIO PARA QUE AL BORRAR EL USUARIO SE BORREN TAMBIÉN SUS IMAGENES

	validates :name, presence: true 
	validates :name, uniqueness: true
	validates :name, length: { maximum: 30 } 
	validates :name, format: { with: /[a-zA-Z\d\s]/ }

	validates :email, presence:true
	validates :email, uniqueness: true

	validates :password, presence: true

	has_secure_password

	def editor? 
 		self.role == 'editor' 
	end

	def admin? 
 		self.role == 'admin' 
	end

	def get_email
		self.email
	end
end

final_project/app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_user, only: [:index, :show, :edit, :destroy]
	before_action :require_admin, only: [:destroy]

	def welcome
		@layout_welcome = false
		#this is because don't want to show the footer in the welcome page
	end

	def about
	end

	def index 
		@users = User.all
	end

	def show
		begin
			@user = User.find params[:id]
		rescue ActiveRecord::RecordNotFound
			render 'no_users_found'
		end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new user_params #aquí se llama al metodo privado project_params (mas abajo)
		if @user.save #si es valido, este .save devuelve true, y se guarda. Y si es false, no lo guarda. Con el save comprueba las validaciones que le pusimos en el modelo del project
			flash[:notice] = "User created successfully"
			session[:user_id] = @user.id
			redirect_to users_path #si es true, lo guarda y te lleva al show del proyecto
		else
			flash[:alert] = "User hasn't been created!"
			redirect_to '/signup' #si es falso, te vuelve a llevar a la vista de projects. Ahora se usa render, porque con el redirect_to, te machaca el proyecto
		end
	end

	def edit
		@user = User.find params[:id]
	end

	def update
		@user = User.find params[:id]
		if @user.update user_params
			redirect_to @user #@project equivale a poner todo el path del show project
		else
			render 'edit'
		end
	end

	def destroy
		user = User.find params[:id] #aqui no hace falta poner @ ya que no necesitamos que ese project sea accesible en la VISTA
		user.destroy
		redirect_to users_path
	end

	private #este private hace que los metodos aqui dentro solo sean accesibles desde esta clase
	def user_params #este metodo SE PUEDE LLAMAR COMO QUIERAS, pero es necesario para que al crear un objeto se autorice su creacion (porque si no nos podrían meter codigo malicioso)
		params.require(:user).permit(:name, :email, :password)
	end

end

final_project/app/helpers/users_helper.rb
module UsersHelper
end

final_project/app/views/users/about.html.erb
<!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
          <p><a class="btn btn-default" href="http://getbootstrap.com/examples/carousel/#" role="button">View details »</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
          <p><a class="btn btn-default" href="http://getbootstrap.com/examples/carousel/#" role="button">View details »</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="http://getbootstrap.com/examples/carousel/#" role="button">View details »</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDUwMCA1MDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjE5MC41IiB5PSIyNTAiIHN0eWxlPSJmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MjNwdDtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj41MDB4NTAwPC90ZXh0PjwvZz48L3N2Zz4=" data-holder-rendered="true">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDUwMCA1MDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjE5MC41IiB5PSIyNTAiIHN0eWxlPSJmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MjNwdDtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj41MDB4NTAwPC90ZXh0PjwvZz48L3N2Zz4=" data-holder-rendered="true">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDUwMCA1MDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjE5MC41IiB5PSIyNTAiIHN0eWxlPSJmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MjNwdDtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj41MDB4NTAwPC90ZXh0PjwvZz48L3N2Zz4=" data-holder-rendered="true">
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->


      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="http://getbootstrap.com/examples/carousel/#">Back to top</a></p>
        <p>© 2014 Company, Inc. · <a href="http://getbootstrap.com/examples/carousel/#">Privacy</a> · <a href="http://getbootstrap.com/examples/carousel/#">Terms</a></p>
      </footer>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaSc

final_project/app/views/users/edit.html.erb
<% if flash[:alert] %>
    <div class="alert alert-warning" role="alert">
        <strong>Oh NO! </strong><%= flash[:alert] %>
    </div>
<% end %>

<% if @user.errors.any? %>
    <div class="alert alert-danger" role="danger">
    	<ul>
    		<% @user.errors.full_messages.each do |error_msg| %>
    			<li><%= error_msg %></li>
    		<% end %>
    	</ul>
    </div>
<% end %>

<div class="container col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4 new-session">

        <h2 class="form-signin-heading">Modify your account</h2>
        <%= form_for @user do |f| %> 
        <%= f.text_field :name, :placeholder => "Change your Name", class: "form-control" %>
        <%= f.email_field :email, :placeholder => "Change your Email", class: "form-control" %>
        <%= f.password_field :password, :placeholder => "Change Password", class: "form-control"%>
        
        <%= f.submit "SAVE", class: "btn btn-primary col-xs-12 col-md-12" %>
        <br>
        <%= link_to("CANCEL", user_path(@user), class: "btn btn-danger col-xs-12 col-md-12") %>
      <% end %>

</div> 

final_project/app/views/users/index.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>

<div class="jumbotron">
    <h1>Users list</h1>
    <p class="lead">Lorem fistrum llevame al sircoo va usté muy cargadoo caballo blanco caballo negroorl por la gloria de mi madre pecador fistro de la pradera por la gloria de mi madre amatomaa.</p>
</div>


<ul>
	<% @users.each do |user| %>
		<% if user.role != 'admin' %>
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title"><%= link_to(user.name, user_path(user)) %></h3>
					
					<% if current_user && current_user.admin? %>
						<%= link_to("- Edit", edit_user_path(user)) %>
						<%= link_to("- Destroy", user_path(user), method: :delete,
						data: {confirm: "Are you sure?"}) %>
					<% end %>	
					<span class="pull-right clickable panel-collapsed"><i class="glyphicon glyphicon-chevron-down"></i></span>		
				</div>

				<div class="panel-body collapse">
					<% user.images.each do |image| %>
							<%= link_to image_tag(image.photo.url(:thumb)), user_image_path(user, image) %>
					<% end %>
				</div>
			</div>
		<% end %>
	<% end %>
</ul>

</div>

final_project/app/views/users/new.html.erb
<% if flash[:alert] %>
    <div class="alert alert-warning" role="alert">
        <strong>Oh NO! </strong><%= flash[:alert] %>
    </div>
<% end %>

<% if @user.errors.any? %>
    <div class="alert alert-danger" role="danger">
        <ul>
            <% @user.errors.full_messages.each do |error_msg| %>
                <li><%= error_msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>


<div class="container col-xs-8 col-xs-offset-2 col-md-4 col-md-offset-4 new-session">

        <h2 class="form-signin-heading">Create new user</h2>
        <%= form_for @user do |f| %> 
        <%= f.text_field :name, :placeholder => "Name", class: "form-control" %>
        <%= f.email_field :email, :placeholder => "Email", class: "form-control" %>
        <%= f.password_field :password, :placeholder => "Password", class: "form-control"%>
        
        <%= f.submit "SAVE", class: "btn btn-primary col-xs-12 col-md-12" %>
        <br>
        <%= link_to("CANCEL", welcome_path, class: "btn btn-danger col-xs-12 col-md-12") %>
      <% end %>

</div> 

final_project/app/views/users/no_users_found.html.erb
<h1 class="alert alert-danger" role="alert"> No users found </h1>

final_project/app/views/users/show.html.erb
<% if flash[:notice] %>
	<br>
	<div class="alert alert-success" role="alert">
	    <%= flash[:notice] %>
	</div>
<% end %>

	<div class="jumbotron">
	    <h1><%= @user.name %></h1>

	    <% if current_user.email != @user.email %>
		    <p class="lead">
		    	Like an image of this user? You want to ask where he took the photos? Send him a message!
		    	<br>	
		    	<a class="btn btn-default" href="" role="button">Send a message <span class="glyphicon glyphicon-envelope"></span></a>
			</p>
		<% else %>
			<p class="lead">
		    	Welcome to your profile, dear <%= @user.name %>
		    	<br><br>
		    	<%= link_to "Add a new image", new_user_image_path(@user), class: "btn btn-default" %>
				<%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-default" %>
		    </p>
		<% end %>
	</div>

<div class="container">

    <% if current_user.email == @user.email && @user.images[0]===nil %>
		<h2>You don't have any images yet, upload one now!</h2>
	<% end %>

	<% @user.images.each do |image| %>
		
		<div class="container col-md-6 photo-large-container">
			<div class="row col-md-12"><%= link_to image_tag(image.photo.url(:large)), user_image_path(@user, image), class: "img-thumbnail"  %></div>
			<h4 class="row col-md-12"><%= image.title %></h4>
			<div class="row col-md-12"><%= image.address %></div>

			<% if current_user && current_user.admin? %>

				<%= link_to(" - Edit Image", edit_user_image_path(@user, image)) %>
				<%= link_to(" - Destroy Image", user_image_path(@user, image), method: :delete,
				data: {confirm: "Are you sure?"}) %>

			<% end %>
		</div>
	<% end %>
	
</div>

final_project/app/views/users/welcome.html.erb
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1" class=""></li>
          <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
        </ol>    
        <div class="carousel-inner" role="listbox">

          <div class="item active">
            <div class="carousel-caption text-welcome">
                  <h1>Upload photos from your favourites places</h1>
                  <p class="hidden-xs">Lorem fistrum dolore a wan no puedor. Magna a peich nostrud está la cosa muy malar te va a hasé pupitaa se calle ustée. Ese que llega papaar papaar hasta luego Lucas ese hombree tiene musho peligro a peich incididunt diodenoo minim. Incididunt mamaar apetecan velit ese hombree. Commodo elit hasta luego Lucas a wan qué dise usteer tiene musho peligro aute incididunt te va a hasé pupitaa jarl se calle ustée.</p>
                  <p><%= link_to "Join us!", 'signup', class: "btn btn-lg btn-primary" %></p>
            </div>
            <img class="welcome-image img-responsive" alt="First slide [1140x500]" src="http://www.mrwallpaper.com/wallpapers/Little-Village-1920x1200.jpg" data-holder-rendered="true">
          </div>

          <div class="item">
            <div class="carousel-caption text-welcome">
                  <h1>Rate the pictures of other users</h1>
                  <p class="hidden-xs">Lorem fistrum apetecan sexuarl jarl está la cosa muy malar a gramenawer hasta luego Lucas te voy a borrar el cerito hasta luego Lucas fistro al ataquerl. Apetecan hasta luego Lucas.</p>
                  <p><%= link_to "Log in", 'login', class: "btn btn-lg btn-primary" %></p>
            </div>
              <img class="welcome-image img-responsive" alt="Second slide [1140x500]" src="http://www.wallpapersdb.org/wallpapers/world/nashville_usa_1920x1200.jpg" data-holder-rendered="true">
            </div>

            <div class="item">
              <div class="carousel-caption text-welcome">
                    <h1>Discover charming places around you</h1>
                    <p class="hidden-xs">Lorem fistrum se calle ustée te va a hasé pupitaa dolore ut por la gloria de mi madre eiusmod está la cosa muy malar. Ut de la pradera cillum aliquip te va a hasé pupitaa ese pedazo de llevame al sircoo quis pecador ese que llega.</p>
                    <p><%= link_to "See the gallery", 'photos', class: "btn btn-lg btn-primary" %></p>
              </div>
              <img class="welcome-image img-responsive" alt="Third slide [1140x500]" src="http://blog.jooble.org/latam/wp-content/uploads/2015/02/ciudad-de-nueva-york_1920x1200_304.jpg" data-holder-rendered="true">
            </div>

        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>

      </div>
    </div>

<footer hidden></footer>